server:
  port: ${EXCEL_SERVER_PORT}

spring:
  datasource:
    url: jdbc:${DB}://${HOST}:${PORT}/${DB_NAME}?rewriteBatchedStatements=true
    username: ${USER}
    password: ${PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: ${FETCH_SIZE}
