server:
  port: ${EXCEL_SERVER_PORT}

spring:
  datasource:
    url: jdbc:${DB}://${DB_HOST}:${DB_PORT}/${DB_NAME}?rewriteBatchedStatements=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: ${FETCH_SIZE}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    template:
      default-receive-queue: ${QUEUE_NAME}
    listener:
      simple:
        concurrency: ${CONCURRENCY}
        max-concurrency: ${MAX_CONCURRENCY}
        prefetch: ${PREFETCH}
        acknowledge-mode: manual
