server:
  port: ${EXCEL_SERVER_PORT}

spring:
  datasource:
    url: jdbc:${DB}://${DB_HOST}:${DB_PORT}/${DB_NAME}?rewriteBatchedStatements=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE}
      connection-timeout: ${DB_CONNECTION_TIMEOUT}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: ${FETCH_SIZE}

minio:
  bucket:
    name: ${MINIO_BUCKET_NAME}
  access:
    key: ${MINIO_KEY}
    secret: ${MINIO_PASSWORD}
  url: ${MINIO_URL}

rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_USER}
  password: ${RABBITMQ_PASSWORD}
  file-create-progress-exchange: ${FILE_CREATE_PROGRESS_EXCHANGE}
  file-create-request-queue: ${FILE_CREATE_REQUEST_QUEUE}
  listener:
    concurrency: ${LISTENER_CONCURRENCY}
    max-concurrency: ${LISTENER_MAX_CONCURRENCY}
    prefetch: ${LISTENER_PREFETCH}